### ISSUE TITLE
Shared Hazelcast Instances Between Multiple Microservices

### ISSUE THREAD

**Issue by tunix** [bitsofinfo/hazelcast-docker-swarm-discovery-spi#13]
Hi @bitsofinfo ,

I've a use case where N microservices start their own Hazelcast instances and form a cluster. I have some shared data between 2 different microservices. However since they're different microservices, I define them seperately in my swarm config and due to `service_name` being mandatory, they won't be able to find each other.

```
service_a:
    ...
    DOCKER_HOST: ...
    ...network_name: internal
    ...service_name: service_a
    ...

service_b:
    ...
    ...network_name: internal
    ...service_name: service_b
    ...
```

I think below would work instead where I don't define the service name but the service labels. (**Question:** I don't see an example for adding service labels, does this plugin look for keys or values?)

```
service_a:
    ...
    DOCKER_HOST: ...
    ...network_name: internal
    ...service_labels: hazelcast
    deploy:
        labels:
            hazelcast: true
    ...

service_b:
    ...
    ...network_name: internal
    ...service_labels: hazelcast
    deploy:
        labels:
            hazelcast: true
    ...
```

I think we can make service names optional as well and check during runtime whether a service name or service label exists. What do you think?

**Comment by tunix** [comment]
Looking at the code, I can see that this was the intended behaviour. (ex: SwarmAddressPicker @ L24, SwarmDiscoveryUtil @ L111-112 , tag: 1.0-RC3) So I think we can make this change?

**Comment by bitsofinfo** [comment]
Both (service names and service labels args) accept multiple names (comma delimited) I use this functionality today. Neither should be required I thought, but sure please do a PR + README update if you'd like that behavior.

**Comment by tunix** [comment]
Sent PR #15

**Comment by bitsofinfo** [comment]
1.0-RC7 is out, thx!
