### ISSUE TITLE
Maven central

### ISSUE THREAD

**Issue by anton-johansson** [bitsofinfo/hazelcast-docker-swarm-discovery-spi#21]
Any plans on pushing this to Maven central instead of jcenter?

**Comment by bitsofinfo** [comment]
no plans

**Comment by PhantomYdn** [comment]
+1 to the question. It's easy and free to do, but will solve problems for developers.
And one more question: are you planning release any time soon?

**Comment by bitsofinfo** [comment]
I'm not entirely clear on the issue, its quite easy to add jcenter, one of the largest repos as well to any build system.

There are no releases planned anytime soon as there are no outstanding PRs etc.
