### ISSUE TITLE
SwarmMemberAddressProvider configuration properties

### ISSUE THREAD

**Issue by robinroos** [bitsofinfo/hazelcast-docker-swarm-discovery-spi#27]
Hello,

When configuring SwarmMemberAddressProvider, which of the following properties are Optional, and is it ok for the property elements (those corresponding to the optional properties) to remain in the hazelcast.xml file without the corresponding environment variables being defined?

```
<!-- Comma delimited list of Docker network names to discover matching services on -->
<property name="docker-network-names">${dockerNetworkNames}</property>
                      
<!-- Comma delimited list of relevant Docker service names to find tasks/containers on the above networks -->
<property name="docker-service-names">${dockerServiceNames}</property>
                      
<!-- Comma delimited list of relevant Docker service label=values to find tasks/containers on the above networks -->
<property name="docker-service-labels">${dockerServiceLabels}</property>
                      
<!-- Swarm Manager URI (overrides DOCKER_HOST) -->
<property name="swarm-mgr-uri">${swarmMgrUri}</property>
                  
<!-- If Swarm Mgr URI is SSL, to enable skip-verify for it -->
<property name="skip-verify-ssl">${skipVerifySsl}</property>
```

Thanks, Robin.

**Comment by bitsofinfo** [comment]
The following should work

Required: `swarm-mgr-uri`, `skip-verify-ssl`, `docker-network-names`

Optionally `docker-service-names` and/or `docker-service-labels`

You should leave all the `<property` definitions even if the value is blank/missing

**Comment by robinroos** [comment]
Ok, that’s great thanks. I should have this deployed pretty quickly.
