### ISSUE TITLE
No service match for given service name criteria

### ISSUE THREAD

**Issue by robinroos** [bitsofinfo/hazelcast-docker-swarm-discovery-spi#35]
Now using RC12 we observe the following:

```
INFO [ips-data-service,,,] 1 --- [           main] o.b.h.d.docker.swarm.SwarmDiscoveryUtil  : discoverNodes(): via DOCKER_HOST: springboot-docker-proxy
INFO [ips-data-service,,,] 1 --- [           main] o.b.h.d.docker.swarm.SwarmDiscoveryUtil  : Found relevant docker network: ips_network[un0i63ypy2vssq4y86ym3y5zi]
INFO [ips-data-service,,,] 1 --- [           main] o.b.h.d.docker.swarm.SwarmDiscoveryUtil  : Invoking criteria-based container discovery for dockerServiceName=data-service
INFO [ips-data-service,,,] 1 --- [           main] o.b.h.d.docker.swarm.SwarmDiscoveryUtil  : Number of services matching given criteria = 0
INFO [ips-data-service,,,] 1 --- [           main] o.b.h.d.docker.swarm.SwarmDiscoveryUtil  : Returning set of discovered containers with size=0
```

which leads directly to the NullPointerException

```
at org.bitsofinfo.hazelcast.discovery.docker.swarm.SwarmMemberAddressProvider.getBindAddress(SwarmMemberAddressProvider.java:237) ~[hazelcast-docker-swarm-discovery-spi-1.0-RC12.jar:na]
```

This indicates that the expected service name "data-service" is not matched by any of the services exposed by the proxy available at 

```
DOCKER_HOST: springboot-docker-proxy
```

**Comment by robinroos** [comment]
PR #34 provides the necessary information.  Examples (from Travis CI, logged then at INFO):

```
INFO: No service match for given criteria
INFO: allServices=[hazelcast-docker-swarm-discovery-spi-test]
```
 
Note that the code execution path already is headed straight towards a NullPointerException.

**Comment by robinroos** [comment]
PR Build is Green.

The INFO message "No service match for given criteria" is correctly absent in Build #160 as the tests do not hit this specific issue for the NullPointerException.

**Comment by bitsofinfo** [comment]
https://github.com/bitsofinfo/hazelcast-docker-swarm-discovery-spi/releases/tag/1.0-RC13

**Comment by robinroos** [comment]
Firstly, thanks for RC13.  I have now read your commits and I can see the significant effort you put into making my PR "good to go", and I really appreciate that.

Two points arising from my work with that build so far:

- serviceName entries must be fully qualified with the stackName, with an underscore between the stackName and the serviceName

In my case, the service "data-service" belongs to the stack "ip_service", so the fully qualified name is "ip_service_data-service".

```
<property name="docker-service-names">ip_service_data-service</property>
```

- the property

```
logAllServiceNamesOnFailedDiscovery
```
is valid within
```
<member-address-provider>
    <properties>
```
which properties are interpreted by this discovery provider, but it is invalid if placed within
```
<discovery-strategies>
    <properties>
```
which properties are interpreted by Hazelcast itself.  Hazelcast will complain as follows if it is provided:
```
Caused by: com.hazelcast.config.InvalidConfigurationException: Unknown properties: '[log-all-service-names-on-failed-discovery]' on discovery strategy
```
Please update the sample documentation https://github.com/bitsofinfo/hazelcast-docker-swarm-discovery-spi/blob/master/src/main/resources/hazelcast-docker-swarm-discovery-spi-example-member-address-provider.xml accordingly.

**Comment by bitsofinfo** [comment]
When you do a `docker service ls` or invoke the docker services APIs to get a list of all services, the names listed there are those intended to be used with this library's service name args.

The property is valid and consumed by the DockerSwarmDiscoveryStrategy class as the test explicitly defines it and consumes it in the test w/ a value of true

```
hazelcast-docker-swarm-discovery-spi-test.1.p18k4fp46vjq@travis-job-4d69884d-a8ff-4a2e-a77e-4690d360434c    | INFO: SwarmDiscoveryUtil[DockerSwarmDiscoveryStrategy].discoverNodes(): via DOCKER_HOST: 10.20.0.113
hazelcast-docker-swarm-discovery-spi-test.1.p18k4fp46vjq@travis-job-4d69884d-a8ff-4a2e-a77e-4690d360434c    | docker-network-names = hazelcast-docker-swarm-discovery-spi-test
hazelcast-docker-swarm-discovery-spi-test.1.p18k4fp46vjq@travis-job-4d69884d-a8ff-4a2e-a77e-4690d360434c    | docker-service-names = hazelcast-docker-swarm-discovery-spi-test
hazelcast-docker-swarm-discovery-spi-test.1.p18k4fp46vjq@travis-job-4d69884d-a8ff-4a2e-a77e-4690d360434c    | docker-service-labels = ${dockerServiceLabels}
hazelcast-docker-swarm-discovery-spi-test.1.p18k4fp46vjq@travis-job-4d69884d-a8ff-4a2e-a77e-4690d360434c    | swarmMgrUri = http://10.20.0.113:2376
hazelcast-docker-swarm-discovery-spi-test.1.p18k4fp46vjq@travis-job-4d69884d-a8ff-4a2e-a77e-4690d360434c    | skipVerifySsl = false
hazelcast-docker-swarm-discovery-spi-test.1.p18k4fp46vjq@travis-job-4d69884d-a8ff-4a2e-a77e-4690d360434c    | logAllServiceNamesOnFailedDiscovery = true
```
