### ISSUE TITLE
Configuring multiple swarm manager nodes

### ISSUE THREAD

**Issue by Seraksab** [bitsofinfo/hazelcast-docker-swarm-discovery-spi#38]
We are currently running on a swarm that has 3 active manager nodes with the discovery configured to use local network binding via SwarmMemberAddressProvider (Option 1).
Currently only 1 of the manager is configured in the DOCKER_HOST variable.

However, the guide states that it should be possible to configure all 3 of them:
>  The DOCKER_HOST environment variable for the container should also be set to a name that resolves to one **or more** swarm manager nodes

How would i specify all 3 of them in the same variable?
As simply providing a list with ',' or ' ' as a delimiter wouldn't work.

I've been trying to find a solution for some time now but am currently unable to solve it. Am i missing something?
Being able to provide multiple managers seems rather crucial with regard to fault tolerance.

Edit: currently on RC8. However looking at the changes i guess this should make a difference.

**Comment by bitsofinfo** [comment]
DOCKER_HOST only takes ONE hostname/ip. So if you want that to have redundancy or point to multiple managers your only option is via DNS (i.e. list multiple ips for that name), or the better solution, just point DOCKER_HOST = to a load balancer for your managers.
