### ISSUE TITLE
Cannot find a matching constructor for MemberAddressProvider implementation 'org.bitsofinfo.hazelcast.discovery.docker.swarm.SwarmMemberAddressProvider'

### ISSUE THREAD

**Issue by jouhami** [bitsofinfo/hazelcast-docker-swarm-discovery-spi#49]
I'm trying to deploy a stack of 2 services with one using hazelcast.

I'm doing the network binding via SwarmMemberAddressProvider

I have this error in _webapp_ service startup : 

`Cannot find a matching constructor for MemberAddressProvider implementation 'org.bitsofinfo.hazelcast.discovery.docker.swarm.SwarmMemberAddressProvider'`

I'm using 1.0-RC14 with Hazelcast 3.12.2

I also tried with Hazelcast 3.9.2 but I got a NPE : 

```
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: com.hazelcast.config.ConfigurationException: Cannot create a new instance of MemberAddressProvider 'class org.bitsofinfo.hazelcast.discovery.docker.swarm.SwarmMemberAddressProvider'
    Caused by: java.lang.RuntimeException: com.hazelcast.config.ConfigurationException: Cannot create a new instance of MemberAddressProvider 'class org.bitsofinfo.hazelcast.discovery.docker.swarm.SwarmMemberAddressProvider'
    Caused by: com.hazelcast.config.ConfigurationException: Cannot create a new instance of MemberAddressProvider 'class org.bitsofinfo.hazelcast.discovery.docker.swarm.SwarmMemberAddressProvider'
    Caused by: java.lang.reflect.InvocationTargetException
    Caused by: java.lang.RuntimeException: SwarmAddressPicker: Error constructing SwarmDiscoveryUtil: null.
```
	
	
Here is my docker-compose.yml file : 

```
version: '3.4'
services:
  db:
    image: mysql/mysql-server:8.0
    command: --log-bin-trust-function-creators=1
    networks:
      - internal-net
    volumes:
      - mysql-data:/var/lib/mysql

  webapp:
    image: webapp:latest
    networks:
      - internal-net
    volumes:
      - webapp-data:/opt/jboss/data
    depends_on:
      - db
    ports:
      - '8443:8443'
    environment:
      JAVA_OPTS: "-DdockerNetworkNames=internal-net \
      -DdockerServiceNames=stackname_webapp \
      -DskipVerifySsl=true \
      -Dhazelcast.config=/opt/jboss/hazelcast-swarm.xml"
```
	  
	  

I'm creating hazelcast instances like this : `Hazelcast.newHazelcastInstance()`

What am I doing wrong ?

**Comment by jouhami** [comment]
I figured out what was the problem. The `hazelcastPeerPort` was not provided (I thought it's optional) and I got a NPE in `SwarmMemberAddressProvider()` constructor.

**Comment by rahuzz** [comment]
I am getting the same error.  "Cannot find a matching constructor for MemberAddressProvider implementation 'org.bitsofinfo.hazelcast.discovery.docker.swarm.SwarmMemberAddressProvider'."

my properties are as below
System.setProperty("dockerNetworkNames", "xxx_dev");
		System.setProperty("dockerServiceLabels", "dev");
		System.setProperty("dockerServiceNames", "servicename");
		System.setProperty("swarmMgrUri", "http://abc.def:1234");
		System.setProperty("skipVerifySsl", "false");
		System.setProperty("logAllServiceNamesOnFailedDiscovery", "false");
		System.setProperty("hazelcastPeerPort", "5701");
		System.setProperty("hazelcastInterface", "");

what should be the value of hazelcastInterface ?
What else I am missing

**Comment by rahuzz** [comment]
Also i am getting "Name of the hazelcast schema location is incorrect, using default"
for value 
<hazelcast id="hazelcast-consul-discovery" 
           xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.7.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
