### ISSUE TITLE
Dont know how to make a search with labels

### ISSUE THREAD

**Issue by kristoflarcher** [bitsofinfo/hazelcast-docker-swarm-discovery-spi#9]
Hi,
We are using your library ( thank you by the way ...)
But we dont know how to configure the search according to labels ?
Do you have a example ?

Regards

**Comment by bitsofinfo** [comment]
See the README `-DdockerServiceLabels=myLabel1,myLabel2` etc (or hardwire in your hz config xml)

```
docker service create \
    --network [mynet] \
    --name myHzService1 \
    -e "DOCKER_HOST=http://[swarmmgr]:[port]" \
    [yourappimage] \
    java \
    -DdockerNetworkNames=[mynet] \
    -DdockerServiceNames=myHzService1 \
    -DdockerServiceLabels=myLabel1,myLabel2 \
    -DhazelcastPeerPort=5701 \
    -jar /test.jar
```

**Comment by kristoflarcher** [comment]
Hi, 
And thank you for your reactivity.
I know how to make a search  with labels  : I tagg my service  with the label exemple.label  = "valeur"

I did a search on key label...but ...nothing happen.. and .i did a search on  value label...and nothing  happen too

It seems that the search on label did not filter results at all.
I would like to understand how I should procede

Regards

**Comment by bitsofinfo** [comment]
Please provide a reproducible sample project demonstrating the issue as I am not following what you are doing exactly.
